name: Host service CI

on: #이벤트가 발생했을떄 jobs 작업이 수행된다.
  push:
    branches: [ "main" ]
    paths: ["*.js"] # 자바스크립트 파일이 바뀔떄만 push 동작이 실행함
    

jobs:
  buildImage: # 이미지를 build 하겟다. 
    runs-on: ubuntu-latest # jobs가 실행될떄마다 container을 띄우는데 기반이 ubuntu - 임최신버전으로 띄우겟다.

    steps: # 작업을 하나 할때마다 이름을 붙이겠다.
    - name: 1. checkout 
      uses: actions/checkout@v3 #checkout은 소스를 가져오는것의미 dangtong/hostservice를 내려받는다.
      #자기가 알아서 현재 파이프라인이 돌아가는 레포지토리를 ubuntu container에 받아옴
      # -name: 1. checkout
      #  run: git config user.email dangtong@gmail.
      #  run: git config user.name dangtong76
      #  run: git pull dangtong/hostservice 와 같다.
    - name: 2. Login to DocdkerHub
      uses: docker/login-action@v2 #login 할때 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} # docker login 할떄 with 안에 있는 변수를 가지고간다.
   #- name: 2.5 Create DOcker tags # TAG값 따로 만들어줘서 넣어줄 수 있음 해쉬값 말고
    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true # docker.io push
        tags: dangtong/hostservice:${{ github.sha }} # 빌드하는 시간마다 해쉬값을 가져와서 버전을 생성

       